set history=10
set noexpandtab
set tabstop=4
set mouse=v
set autoread
au FocusGained,BufEnter * checktime
set smartcase
set hlsearch
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2
set linespace=0
set whichwrap+=<,>,b,s,[,]
syntax enable
set regexpengine=0
set encoding=utf8
set ffs=unix,dos
set nobackup
set nowb
set noswapfile
