set history=10
set number
set noexpandtab
set tabstop=4
set mouse=a
set autoread
au FocusGained,BufEnter * checktime
set smartcase
set hlsearch
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2
set linespace=0
set whichwrap+=<,>,b,s,[,]
syntax enable
set regexpengine=0
let g:solarized_termcolors=256
set background=dark
colorscheme solarized
set t_Co=256
set encoding=utf8
set ffs=unix
set nobackup
set nowb
set noswapfile
set clipboard=unnamedplus
